name: Run API Tests

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Personal Access Token'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest tests with Allure reporting
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
        run: |
          pytest
